version: '3'
services:
  attendance-alarm:
    restart: always
    container_name: jmusicbot-jp
    build: https://github.com/Cosgy-Dev/JMusicBot-JP.git
    volumes:
      - "./data/config.txt:/opt/jmusicbot/config.txt"
      - "./data/serversettings.json:/opt/jmusicbot/serversettings.json"
      - "./data/Publist:/opt/jmusicbot/Publist"
      - "./data/logs:/opt/jmusicbot/logs"
